/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smsproject;

import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Shaariful Islam
 */
public class PaymentSection extends javax.swing.JFrame {

    /**
     * Creates new form PaymentSection
     */
    public PaymentSection() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        com1 = new javax.swing.JComboBox<>();
        id = new javax.swing.JTextField();
        amount = new javax.swing.JTextField();
        com2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        lblimg = new javax.swing.JLabel();
        lblmsg = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(900, 550));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        com1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CLASS ONE", "CLASS TWO", "CLASS THREE", "CLASS FOUR", "CLASS FIVE" }));
        jPanel1.add(com1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 350, 47));

        id.setBackground(new java.awt.Color(0, 102, 102));
        id.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        id.setForeground(new java.awt.Color(255, 255, 255));
        id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        id.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idKeyReleased(evt);
            }
        });
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 210, 33));

        amount.setBackground(new java.awt.Color(0, 102, 102));
        amount.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        amount.setForeground(new java.awt.Color(255, 255, 255));
        amount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        amount.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 210, 33));

        com2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "JANUARY", "FEBRUARY", "MARCH", "APRIL", "MAY", "JUNE", "JULY", "AUGUST", "SEPTEMBER", "OCTOBER", "NOVEMBER", "DECEMBER" }));
        jPanel1.add(com2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 302, 47));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AMOUNT");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 120, 33));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PAYMENT SECTION");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 330, 33));

        name.setBackground(new java.awt.Color(0, 102, 102));
        name.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        name.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 210, 33));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("NAME");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 77, 33));

        jButton1.setBackground(new java.awt.Color(204, 204, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, 210, 50));

        jLabel8.setFont(new java.awt.Font("Yu Gothic Medium", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("X");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, 50, 60));

        date.setBackground(new java.awt.Color(0, 102, 102));
        date.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        date.setForeground(new java.awt.Color(255, 255, 255));
        date.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        date.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 210, 33));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("DATE");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 77, 33));

        lblimg.setForeground(new java.awt.Color(255, 255, 255));
        lblimg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblimg.setText("IMAGE");
        jPanel1.add(lblimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 270, 210));

        lblmsg.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        lblmsg.setForeground(new java.awt.Color(255, 255, 255));
        lblmsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblmsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 210, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 77, 33));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
public void paysend() {
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/alokito", "root", "password");
            System.out.println("Success");
            String classname = com1.getSelectedItem().toString();
            String month = com2.getSelectedItem().toString();
            int idd = Integer.parseInt(id.getText());
            String names = name.getText();
            int amo = Integer.parseInt(amount.getText());
            String dates = date.getText();
            PreparedStatement stm = conn.prepareStatement("INSERT INTO payment values(?,?,?,?,?,?)");
            stm.setInt(1, idd);
            stm.setString(2, names);
            stm.setString(3, classname);
            stm.setString(4, month);
            stm.setInt(5, amo);
            stm.setString(6, dates);

            stm.executeUpdate();

        } catch (Exception e) {
            System.out.println("" + e);
        }
    }

    public void changeimg() {
        byte[] imagebyte;
        Image image;
        
        String classname = com1.getSelectedItem().toString();
        if (id.getText().isEmpty()) {
           //int idd = Integer.parseInt(id.getText());
            lblmsg.setText("SELECT ROLL");
            name.setText("");
        } else {
            if (classname.equals("CLASS ONE")) {
                int idd = Integer.parseInt(id.getText());
            try {
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/alokito", "root", "password");
                System.out.println("Success");

                PreparedStatement stm = conn.prepareStatement("select name, img from classone where id=?");
                stm.setInt(1, idd);

                ResultSet res = stm.executeQuery();
                while (res.next()) {
                    imagebyte = res.getBytes(2);
                    image = getToolkit().createImage(imagebyte);
                    Image im2 = image.getScaledInstance(lblimg.getWidth(), lblimg.getHeight(), Image.SCALE_SMOOTH);
                    ImageIcon icon = new ImageIcon(im2);
                    lblimg.setIcon(icon);
                    name.setText(res.getString(1));
                }
            } catch (Exception e) {
                System.out.println("" + e);
            }
        }else if (classname.equals("CLASS TWO")) {
            int idd = Integer.parseInt(id.getText());
            try {
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/alokito", "root", "password");
                System.out.println("Success");

                PreparedStatement stm = conn.prepareStatement("select name, img from classtwo where id=?");
                stm.setInt(1, idd);

                ResultSet res = stm.executeQuery();
                while (res.next()) {
                    imagebyte = res.getBytes(2);
                    image = getToolkit().createImage(imagebyte);
                    Image im2 = image.getScaledInstance(lblimg.getWidth(), lblimg.getHeight(), Image.SCALE_SMOOTH);
                    ImageIcon icon = new ImageIcon(im2);
                    lblimg.setIcon(icon);
                    name.setText(res.getString(1));
                }
            } catch (Exception e) {
               System.out.println("" + e);
            }
        }else if (classname.equals("CLASS THREE")) {
            int idd = Integer.parseInt(id.getText());
            try {
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/alokito", "root", "password");
                System.out.println("Success");

                PreparedStatement stm = conn.prepareStatement("select name, img from classthree where id=?");
                stm.setInt(1, idd);

                ResultSet res = stm.executeQuery();
                while (res.next()) {
                    imagebyte = res.getBytes(2);
                    image = getToolkit().createImage(imagebyte);
                    Image im2 = image.getScaledInstance(lblimg.getWidth(), lblimg.getHeight(), Image.SCALE_SMOOTH);
                    ImageIcon icon = new ImageIcon(im2);
                    lblimg.setIcon(icon);
                    name.setText(res.getString(1));
                }
            } catch (Exception e) {
                System.out.println("" + e);
            }
        }else if (classname.equals("CLASS FOUR")) {
            int idd = Integer.parseInt(id.getText());
            try {
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/alokito", "root", "password");
                System.out.println("Success");

                PreparedStatement stm = conn.prepareStatement("select name, img from classfour where id=?");
                stm.setInt(1, idd);

                ResultSet res = stm.executeQuery();
                while (res.next()) {
                    imagebyte = res.getBytes(2);
                    image = getToolkit().createImage(imagebyte);
                    Image im2 = image.getScaledInstance(lblimg.getWidth(), lblimg.getHeight(), Image.SCALE_SMOOTH);
                    ImageIcon icon = new ImageIcon(im2);
                    lblimg.setIcon(icon);
                    name.setText(res.getString(1));
                }
            } catch (Exception e) {
               // System.out.println("" + e);
            }
        }else if (classname.equals("CLASS FIVE")) {
            int idd = Integer.parseInt(id.getText());
            try {
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/alokito", "root", "password");
                System.out.println("Success");

                PreparedStatement stm = conn.prepareStatement("select name, img from classfive where id=?");
                stm.setInt(1, idd);

                ResultSet res = stm.executeQuery();
                while (res.next()) {
                    imagebyte = res.getBytes(2);
                    image = getToolkit().createImage(imagebyte);
                    Image im2 = image.getScaledInstance(lblimg.getWidth(), lblimg.getHeight(), Image.SCALE_SMOOTH);
                    ImageIcon icon = new ImageIcon(im2);
                    lblimg.setIcon(icon);
                    name.setText(res.getString(1));
                }
            } catch (Exception e) {
                //System.out.println("" + e);
            }
        }
        }
        
    }
    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        paysend();
        JOptionPane.showMessageDialog(null, "PAYEMENT COMPLETED");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyReleased
        changeimg();
    }//GEN-LAST:event_idKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentSection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentSection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentSection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentSection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentSection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amount;
    private javax.swing.JComboBox<String> com1;
    private javax.swing.JComboBox<String> com2;
    private javax.swing.JTextField date;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblimg;
    private javax.swing.JLabel lblmsg;
    private javax.swing.JTextField name;
    // End of variables declaration//GEN-END:variables
}
