/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smsproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author Shaariful Islam
 */
public class PreapareResult extends javax.swing.JFrame {

    /**
     * Creates new form PreapareResult
     */
    public PreapareResult() {
        initComponents();
        change();
        // nameauto();
        nameauto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        comclass = new javax.swing.JComboBox<>();
        comroll = new javax.swing.JComboBox<>();
        comterm = new javax.swing.JComboBox<>();
        name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        bn1s = new javax.swing.JTextField();
        bn1o = new javax.swing.JTextField();
        bn2s = new javax.swing.JTextField();
        bn2o = new javax.swing.JTextField();
        en1 = new javax.swing.JTextField();
        en2 = new javax.swing.JTextField();
        enavg = new javax.swing.JTextField();
        eng = new javax.swing.JTextField();
        maths = new javax.swing.JTextField();
        matho = new javax.swing.JTextField();
        mathttl = new javax.swing.JTextField();
        rls = new javax.swing.JTextField();
        rlo = new javax.swing.JTextField();
        icts = new javax.swing.JTextField();
        icto = new javax.swing.JTextField();
        rlttl = new javax.swing.JTextField();
        ictttl = new javax.swing.JTextField();
        rlg = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        bn1ttl = new javax.swing.JTextField();
        bng = new javax.swing.JTextField();
        ictg = new javax.swing.JTextField();
        mathg = new javax.swing.JTextField();
        bn2ttl = new javax.swing.JTextField();
        bnavg = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comclass.setBackground(new java.awt.Color(102, 0, 102));
        comclass.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        comclass.setForeground(new java.awt.Color(255, 255, 255));
        comclass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CLASS ONE", "CLASS TWO", "CLASS THREE", "CLASS FOUR", "CLASS FIVE" }));
        comclass.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comclassItemStateChanged(evt);
            }
        });
        jPanel1.add(comclass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 230, 40));

        comroll.setBackground(new java.awt.Color(102, 0, 102));
        comroll.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        comroll.setForeground(new java.awt.Color(255, 255, 255));
        comroll.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comroll.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comrollItemStateChanged(evt);
            }
        });
        jPanel1.add(comroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 250, 40));

        comterm.setBackground(new java.awt.Color(102, 0, 102));
        comterm.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        comterm.setForeground(new java.awt.Color(255, 255, 255));
        comterm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FIRST TERM", "SECOND TERM", "THIRD TERM" }));
        jPanel1.add(comterm, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, 230, 40));

        name.setBackground(new java.awt.Color(102, 0, 102));
        name.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 70, 210, 40));

        jLabel3.setBackground(new java.awt.Color(0, 153, 204));
        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("STUDENT NAME");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 30, 230, 30));

        jLabel6.setBackground(new java.awt.Color(0, 153, 204));
        jLabel6.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 204));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("SELECT CLASS");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 25, 230, 30));

        jLabel7.setBackground(new java.awt.Color(0, 153, 204));
        jLabel7.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 204));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("SELECT ROLL");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 230, 30));

        jLabel8.setBackground(new java.awt.Color(0, 153, 204));
        jLabel8.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 204));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("SELECT TERM");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 230, 30));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 204)));
        jTable1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(153, 0, 102));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"80-100", "A+", "5"},
                {"70-79", "A", "4"},
                {"60-69", "A-", "3.5"},
                {"50-59", "B", "3"},
                {"40-49", "C", "2"},
                {"33-39", "D", "1"},
                {"00-32", "F", "0"}
            },
            new String [] {
                "NUMBER", "POINTS", "GRADE"
            }
        ));
        jTable1.setEnabled(false);
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jTable1.setRowHeight(20);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 170, 270, 200));

        jLabel2.setBackground(new java.awt.Color(0, 102, 204));
        jLabel2.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("BANGLA FIRST");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 195, -1, 30));

        jLabel4.setBackground(new java.awt.Color(0, 102, 204));
        jLabel4.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("BANGLA SECOND");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 245, -1, 30));

        jLabel5.setBackground(new java.awt.Color(0, 102, 204));
        jLabel5.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("ENGLISH FIRST");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 295, -1, 30));

        jLabel9.setBackground(new java.awt.Color(0, 102, 204));
        jLabel9.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("ENGLISH SECOND");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 345, -1, 30));

        jLabel10.setBackground(new java.awt.Color(0, 102, 204));
        jLabel10.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("GENERAL MATH");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 405, -1, 30));

        jLabel11.setBackground(new java.awt.Color(0, 102, 204));
        jLabel11.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("RELIGION");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 455, -1, 30));

        jLabel12.setBackground(new java.awt.Color(0, 102, 204));
        jLabel12.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("ICT");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 505, 30, 30));

        bn1s.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        bn1s.setForeground(new java.awt.Color(102, 0, 102));
        bn1s.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(bn1s, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 60, 40));

        bn1o.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        bn1o.setForeground(new java.awt.Color(102, 0, 102));
        bn1o.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bn1o.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                bn1oKeyReleased(evt);
            }
        });
        jPanel1.add(bn1o, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 60, 40));

        bn2s.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        bn2s.setForeground(new java.awt.Color(102, 0, 102));
        bn2s.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(bn2s, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 60, 40));

        bn2o.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        bn2o.setForeground(new java.awt.Color(102, 0, 102));
        bn2o.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bn2o.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                bn2oKeyReleased(evt);
            }
        });
        jPanel1.add(bn2o, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 60, 40));

        en1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        en1.setForeground(new java.awt.Color(102, 0, 102));
        en1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(en1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 60, 30));

        en2.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        en2.setForeground(new java.awt.Color(102, 0, 102));
        en2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        en2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                en2KeyReleased(evt);
            }
        });
        jPanel1.add(en2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 60, 30));

        enavg.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        enavg.setForeground(new java.awt.Color(102, 0, 102));
        enavg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(enavg, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 320, 60, 40));

        eng.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        eng.setForeground(new java.awt.Color(102, 0, 102));
        eng.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        eng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                engActionPerformed(evt);
            }
        });
        jPanel1.add(eng, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 320, 60, 40));

        maths.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        maths.setForeground(new java.awt.Color(102, 0, 102));
        maths.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(maths, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 60, 40));

        matho.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        matho.setForeground(new java.awt.Color(102, 0, 102));
        matho.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        matho.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mathoKeyReleased(evt);
            }
        });
        jPanel1.add(matho, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 400, 60, 40));

        mathttl.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        mathttl.setForeground(new java.awt.Color(102, 0, 102));
        mathttl.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mathttl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mathttlActionPerformed(evt);
            }
        });
        jPanel1.add(mathttl, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, 60, 40));

        rls.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        rls.setForeground(new java.awt.Color(102, 0, 102));
        rls.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(rls, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, 60, 40));

        rlo.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        rlo.setForeground(new java.awt.Color(102, 0, 102));
        rlo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rlo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rloKeyReleased(evt);
            }
        });
        jPanel1.add(rlo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 450, 60, 40));

        icts.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        icts.setForeground(new java.awt.Color(102, 0, 102));
        icts.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(icts, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 500, 60, 40));

        icto.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        icto.setForeground(new java.awt.Color(102, 0, 102));
        icto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        icto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ictoKeyReleased(evt);
            }
        });
        jPanel1.add(icto, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 500, 60, 40));

        rlttl.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        rlttl.setForeground(new java.awt.Color(102, 0, 102));
        rlttl.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rlttl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rlttlActionPerformed(evt);
            }
        });
        jPanel1.add(rlttl, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 450, 60, 40));

        ictttl.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        ictttl.setForeground(new java.awt.Color(102, 0, 102));
        ictttl.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(ictttl, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 500, 60, 40));

        rlg.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        rlg.setForeground(new java.awt.Color(102, 0, 102));
        rlg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rlg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rlgActionPerformed(evt);
            }
        });
        jPanel1.add(rlg, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 450, 60, 40));

        jLabel13.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 51, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("GRADING SYSTEM");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 140, 260, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 51, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("SUBJECTIVE");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 120, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 51, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("OBJECTIVE");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 120, 30));

        jLabel16.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 51, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("TOTAL");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 80, 30));

        jLabel17.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 51, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("AVG");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, 70, 30));

        bn1ttl.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        bn1ttl.setForeground(new java.awt.Color(102, 0, 102));
        bn1ttl.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(bn1ttl, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 60, 40));

        bng.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        bng.setForeground(new java.awt.Color(102, 0, 102));
        bng.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bngActionPerformed(evt);
            }
        });
        jPanel1.add(bng, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 220, 60, 40));

        ictg.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        ictg.setForeground(new java.awt.Color(102, 0, 102));
        ictg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ictg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ictgActionPerformed(evt);
            }
        });
        jPanel1.add(ictg, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 500, 60, 40));

        mathg.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        mathg.setForeground(new java.awt.Color(102, 0, 102));
        mathg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mathg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mathgActionPerformed(evt);
            }
        });
        jPanel1.add(mathg, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 400, 60, 40));

        bn2ttl.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        bn2ttl.setForeground(new java.awt.Color(102, 0, 102));
        bn2ttl.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bn2ttl.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                bn2ttlCaretUpdate(evt);
            }
        });
        bn2ttl.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                bn2ttlCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        bn2ttl.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                bn2ttlPropertyChange(evt);
            }
        });
        bn2ttl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                bn2ttlKeyReleased(evt);
            }
        });
        jPanel1.add(bn2ttl, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 60, 40));

        bnavg.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        bnavg.setForeground(new java.awt.Color(102, 0, 102));
        bnavg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bnavg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnavgActionPerformed(evt);
            }
        });
        bnavg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                bnavgKeyReleased(evt);
            }
        });
        jPanel1.add(bnavg, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, 60, 40));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 460, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 460, 10));

        jLabel18.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 51, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("GRADE");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 140, 70, 30));

        jButton1.setBackground(new java.awt.Color(153, 0, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("PUBLISH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 450, 270, 40));

        jButton2.setText("DEFAULT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 520, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 77, 1100, 580));

        jPanel2.setBackground(new java.awt.Color(153, 0, 153));

        jLabel19.setFont(new java.awt.Font("Yu Gothic Medium", 1, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("X");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PREAPARE RESULT");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(337, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(235, 235, 235)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 80));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void change() {
        String tablename = comclass.getSelectedItem().toString();

        //Class.forName("com.mysql.jdbc.Driver");
        if (tablename.equals("CLASS ONE")) {
            try {
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/alokito", "root", "root");
                System.out.println("Success");
                PreparedStatement stm = conn.prepareStatement("select * from classone");

                ResultSet res = stm.executeQuery();
                comroll.removeAllItems();

                while (res.next()) {
                    comroll.addItem("" + res.getInt(1));
                    //name.setText(res.getString(2));
                }

            } catch (Exception e) {
                System.out.println("" + e);
            }

        } else if (tablename.equals("CLASS TWO")) {
            try {
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/alokito", "root", "root");
                System.out.println("Success");
                PreparedStatement stm = conn.prepareStatement("select * from classtwo");

                ResultSet res = stm.executeQuery();
                comroll.removeAllItems();

                while (res.next()) {
                    comroll.addItem("" + res.getInt(1));
                }
            } catch (Exception e) {
                System.out.println("" + e);
            }
        } else if (tablename.equals("CLASS THREE")) {
            try {
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/alokito", "root", "root");
                System.out.println("Success");
                PreparedStatement stm = conn.prepareStatement("select * from classthree");

                ResultSet res = stm.executeQuery();
                comroll.removeAllItems();

                while (res.next()) {
                    comroll.addItem("" + res.getInt(1));
                }
            } catch (Exception e) {
                System.out.println("" + e);
            }
        } else if (tablename.equals("CLASS FOUR")) {
            try {
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/alokito", "root", "root");
                System.out.println("Success");
                PreparedStatement stm = conn.prepareStatement("select * from classfour");

                ResultSet res = stm.executeQuery();
                comroll.removeAllItems();

                while (res.next()) {
                    comroll.addItem("" + res.getInt(1));
                }
            } catch (Exception e) {
                System.out.println("" + e);
            }
        } else if (tablename.equals("CLASS FIVE")) {
            try {
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/alokito", "root", "root");
                System.out.println("Success");
                PreparedStatement stm = conn.prepareStatement("select * from classfive");

                ResultSet res = stm.executeQuery();
                comroll.removeAllItems();

                while (res.next()) {
                    comroll.addItem("" + res.getInt(1));
                }
            } catch (Exception e) {
                System.out.println("" + e);
            }
        }
    }

    public void nameauto() {
        String tablename = comclass.getSelectedItem().toString();
        
        //change();
        if (tablename.equals("CLASS ONE")) {
            try {
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/alokito", "root", "root");
                System.out.println("Success");
                PreparedStatement stm = conn.prepareStatement("select * from classone where id=?");
                int idd = Integer.parseInt(comroll.getSelectedItem().toString());
                stm.setInt(1, idd);
                ResultSet res = stm.executeQuery();
                while (res.next()) {
                    name.setText(res.getString(2));
                }
            } catch (Exception e) {
            }
        }else if (tablename.equals("CLASS TWO")) {
            try {
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/alokito", "root", "root");
                System.out.println("Success");
                PreparedStatement stm = conn.prepareStatement("select * from classtwo where id=?");
                int idd = Integer.parseInt(comroll.getSelectedItem().toString());
                stm.setInt(1, idd);
                ResultSet res = stm.executeQuery();
                while (res.next()) {
                    name.setText(res.getString(2));
                }
            } catch (Exception e) {
            }
        }else if (tablename.equals("CLASS THREE")) {
            try {
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/alokito", "root", "root");
                System.out.println("Success");
                PreparedStatement stm = conn.prepareStatement("select * from classthree where id=?");
                int idd = Integer.parseInt(comroll.getSelectedItem().toString());
                stm.setInt(1, idd);
                ResultSet res = stm.executeQuery();
                while (res.next()) {
                    name.setText(res.getString(2));
                }
            } catch (Exception e) {
            }
        }else if (tablename.equals("CLASS FOUR")) {
            try {
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/alokito", "root", "root");
                System.out.println("Success");
                PreparedStatement stm = conn.prepareStatement("select * from classfour where id=?");
                int idd = Integer.parseInt(comroll.getSelectedItem().toString());
                stm.setInt(1, idd);
                ResultSet res = stm.executeQuery();
                while (res.next()) {
                    name.setText(res.getString(2));
                }
            } catch (Exception e) {
            }
        }else if (tablename.equals("CLASS FIVE")) {
            try {
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/alokito", "root", "root");
                System.out.println("Success");
                PreparedStatement stm = conn.prepareStatement("select * from classfive where id=?");
                int idd = Integer.parseInt(comroll.getSelectedItem().toString());
                stm.setInt(1, idd);
                ResultSet res = stm.executeQuery();
                while (res.next()) {
                    name.setText(res.getString(2));
                }
            } catch (Exception e) {
            }
        }

    }

    public void marksauto() {
        System.out.println("BANGLA ONE");
        if (bn1o.getText().equals("")) {
            bnavg.setText("");
            bn1ttl.setText("");
            bng.setText("");
            System.out.println("B");
        } else {

            int bng1s = Integer.parseInt(bn1s.getText());
            int bng1o = Integer.parseInt(bn1o.getText());
            int total = bng1s + bng1o;
            System.out.println("" + total);
            bn1ttl.setText("" + total);
        }
        System.out.println("BANGLA TWO");
        if (bn2o.getText().equals("")) {
            bnavg.setText("");
            bn2ttl.setText("");
            bng.setText("");
            System.out.println("Bangla two true");
        } else {
            int bng2s = Integer.parseInt(bn2s.getText());
            int bng2o = Integer.parseInt(bn2o.getText());
            int total = bng2s + bng2o;
            System.out.println("" + total);
            bn2ttl.setText("" + total);
            System.out.println("Bangla two false");
        }
        System.out.println("ENGLISH ONE");
        if (en2.getText().equals("")) {
            enavg.setText("");
            eng.setText("");
        } else {
            int eng1 = Integer.parseInt(en1.getText());
            int eng2 = Integer.parseInt(en2.getText());
            int total = eng1 + eng2;
            int avg = total / 2;
            enavg.setText("" + avg);
        }
        System.out.println("ENGLISH MATH");
        if (matho.getText().equals("")) {
            mathttl.setText("");
            mathg.setText("");

        } else {
            double mathss = Double.parseDouble(maths.getText());
            double mathso = Double.parseDouble(matho.getText());
            double total = mathss + mathso;
            mathttl.setText("" + total);
        }
        System.out.println("SUBJECT RELIGION");
        if (rlo.getText().equals("")) {
            rlttl.setText("");
            rlg.setText("");

        } else {
            int rlgs = Integer.parseInt(rls.getText());
            int rlgo = Integer.parseInt(rlo.getText());
            int total = rlgs + rlgo;
            rlttl.setText("" + total);
        }

        System.out.println("SUBJECT ICT");
        if (icto.getText().equals("")) {
            ictttl.setText("");
            ictg.setText("");

        } else {
            int ictss = Integer.parseInt(icts.getText());
            int ictso = Integer.parseInt(icto.getText());
            int total = ictss + ictso;
            ictttl.setText("" + total);
        }

    }

    public void banglaresultauto() {
        double Aplus=5.0;
        double A=4.0;
        double Aminus=3.5;
        double B=3.0;
        double C=2.0;
        double D=1.0;
        double F=0.0;
        if (bn1o.getText().equals("") || bn2o.getText().equals("")) {
            bn1ttl.setText("");
            bn2ttl.setText("");
            bnavg.setText("");
            bng.setText("");
        } else {
            int bng1toatl = Integer.parseInt(bn1ttl.getText());
            int bng2total = Integer.parseInt(bn2ttl.getText());
            int total = bng1toatl + bng2total;
            double avg = total / 2;
            bnavg.setText("" + avg);
            if (avg >= 80 && avg <= 100) {
                bng.setText(""+Aplus);
            } else if (avg >= 70 && avg < 80) {
                bng.setText(""+A);
            } else if (avg >= 60 && avg < 70) {
                bng.setText(""+Aminus);
            } else if (avg >= 50 && avg < 60) {
                bng.setText(""+B);
            } else if (avg >= 40 && avg < 50) {
                bng.setText(""+C);
            } else if (avg >= 33 && avg < 40) {
                bng.setText(""+D);
            } else if (avg >= 0 && avg < 33) {
                bng.setText(""+F);
            }
        }

    }

    public void englishresultauto() {
        double Aplus=5.0;
        double A=4.0;
        double Aminus=3.5;
        double B=3.0;
        double C=2.0;
        double D=1.0;
        double F=0.0;
        if (en2.getText().equals("")) {
            enavg.setText("");
            eng.setText("");
        } else {
            double engaverage = Integer.parseInt(enavg.getText());
            if (engaverage >= 80 && engaverage <= 100) {
                eng.setText(""+Aplus);
            } else if (engaverage >= 70 && engaverage < 80) {
                eng.setText(""+A);
            } else if (engaverage >= 60 && engaverage < 70) {
                eng.setText(""+Aminus);
            } else if (engaverage >= 50 && engaverage < 60) {
                eng.setText(""+B);
            } else if (engaverage >= 40 && engaverage < 50) {
                eng.setText(""+C);
            } else if (engaverage >= 33 && engaverage < 40) {
                eng.setText(""+D);
            } else if (engaverage >= 0 && engaverage < 33) {
                eng.setText(""+F);
            }
        }

    }

    public void mathsresultauto() {
        double Aplus=5.0;
        double A=4.0;
        double Aminus=3.5;
        double B=3.0;
        double C=2.0;
        double D=1.0;
        double F=0.0;
        if (matho.getText().equals("")) {
            mathttl.setText("");
            mathg.setText("");
        } else {
            double mathsttl = Double.parseDouble(mathttl.getText());
            if (mathsttl >= 80.0 && mathsttl <= 100.0) {
                mathg.setText(""+Aplus);
            } else if (mathsttl >= 70.0 && mathsttl < 80.0) {
                mathg.setText(""+A);
            } else if (mathsttl >= 60.0 && mathsttl < 70.0) {
                mathg.setText(""+Aminus);
            } else if (mathsttl >= 50.0 && mathsttl < 60.0) {
                mathg.setText(""+B);
            } else if (mathsttl >= 40.0 && mathsttl < 50.0) {
                mathg.setText(""+C);
            } else if (mathsttl >= 33.0 && mathsttl < 40.0) {
                mathg.setText(""+D);
            } else if (mathsttl >= 0.0 && mathsttl < 33.0) {
                mathg.setText(""+F);
            }
        }

    }

    public void relresultauto() {
        if (rlttl.getText().equals("")) {
            rlg.setText("");
        } else {
            double relttl = Double.parseDouble(rlttl.getText());
            if (relttl >= 80 && relttl <= 100) {
                rlg.setText("5");
            } else if (relttl >= 70 && relttl < 80) {
                rlg.setText("4");
            } else if (relttl >= 60 && relttl < 70) {
                rlg.setText("3.5");
            } else if (relttl >= 50 && relttl < 60) {
                rlg.setText("3");
            } else if (relttl >= 40 && relttl < 50) {
                rlg.setText("2");
            } else if (relttl >= 33 && relttl < 40) {
                rlg.setText("1");
            } else if (relttl >= 0 && relttl < 33) {
                rlg.setText("0");
            }
        }

    }

    public void ictresultauto() {
        if (ictttl.getText().equals("")) {
            ictg.setText("");
        } else {
            double ictttls = Double.parseDouble(ictttl.getText());
            if (ictttls >= 80 && ictttls <= 100) {
                ictg.setText("5");
            } else if (ictttls >= 70 && ictttls < 80) {
                ictg.setText("4");
            } else if (ictttls >= 60 && ictttls < 70) {
                ictg.setText("3.5");
            } else if (ictttls >= 50 && ictttls < 60) {
                ictg.setText("3");
            } else if (ictttls >= 40 && ictttls < 50) {
                ictg.setText("2");
            } else if (ictttls >= 33 && ictttls < 40) {
                ictg.setText("1");
            } else if (ictttls >= 0 && ictttls < 33) {
                ictg.setText("0");
            }
        }

    }
//     public String gradesub(){
//         double gpbn = Double.parseDouble(bng.getText());
//        double gpen = Double.parseDouble(eng.getText());
//        double gpmath = Double.parseDouble(mathg.getText());
//        double gprel = Double.parseDouble(rlg.getText());
//        double gpict = Double.parseDouble(ictg.getText());
//        
//        String gradeB=gradeforall(gpbn);
//        String gradeE=gradeforall(gpen);
//        String gradeM=gradeforall(gpmath);
//        String gradeR=gradeforall(gprel);
//        String gradeI=gradeforall(gpict);
//        
//       
//        
//     }
     public String gradeforall(double cgpa){
         String result="";
         if (cgpa>=5.0) {
            result="A+";
        }else if(cgpa>=4.0 && cgpa<5.0){
            result="A";
        }else if(cgpa>=3.5 && cgpa<4.0){
            result="A-";
        }else if(cgpa>=3.0 && cgpa<3.5){
            result="B";
        }else if(cgpa>=2.0 && cgpa<3.0){
            result="C";
        }else if(cgpa>=1.0 && cgpa<2.0){
            result="D";
        }else if(cgpa>=0.0 && cgpa<1.0){
            result="F";
        }
        return result;
     }
    public String gradeprepare(){
        double gpbn = Double.parseDouble(bng.getText());
        double gpen = Double.parseDouble(eng.getText());
        double gpmath = Double.parseDouble(mathg.getText());
        double gprel = Double.parseDouble(rlg.getText());
        double gpict = Double.parseDouble(ictg.getText());
        double totalgp = gpbn+gpen+gpmath+gprel+gpict;
        double cgpa= totalgp/4;
        System.out.println("cgpa=="+cgpa);
        String result="";
        if (cgpa>=5.0) {
            result="A+";
        }else if(cgpa>=4.0 && cgpa<5.0){
            result="A";
        }else if(cgpa>=3.5 && cgpa<4.0){
            result="A-";
        }else if(cgpa>=3.0 && cgpa<3.5){
            result="B";
        }else if(cgpa>=2.0 && cgpa<3.0){
            result="C";
        }else if(cgpa>=1.0 && cgpa<2.0){
            result="D";
        }else if(cgpa>=0.0 && cgpa<1.0){
            result="F";
        }
        return result;
    }
    public void resultpush(){
        String tablename = comclass.getSelectedItem().toString();
        String term = comterm.getSelectedItem().toString();
        if (tablename.equals("CLASS ONE")) {
             try {
            // Class.forName("com.mysql.jdbc.Driver);
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/alokito","root","root");
            PreparedStatement stm = conn.prepareStatement("INSERT INTO resultone VALUES(?,?,?,?,?,?,?,?,?,?,?)");
            String status = gradeprepare();
            double idd= Integer.parseInt(comroll.getSelectedItem().toString());
            String names = name.getText();
            double bangla1 = Double.parseDouble(bn1ttl.getText());
            double bangla2 = Double.parseDouble(bn2ttl.getText());
            double english1 = Double.parseDouble(en1.getText());
            double english2 = Double.parseDouble(en2.getText());
            double maths = Double.parseDouble(mathg.getText());
            double religion = Double.parseDouble(rlg.getText());
            double ict = Double.parseDouble(ictg.getText());
            stm.setDouble(1, idd);
            stm.setString(2, names);
            stm.setDouble(3, bangla1);
            stm.setDouble(4, bangla2);
            stm.setDouble(5, english1);
            stm.setDouble(6, english2);
            stm.setDouble(7, maths);
            stm.setDouble(8, religion);
            stm.setDouble(9, ict);
            stm.setString(10, status);
            stm.setString(11, term);
            stm.executeUpdate();
                 System.out.println("RESULT PUBLISHED CLASS ONE");
            conn.close();
        } catch (Exception e) {
            System.out.println(""+e);
        }
        }else if (tablename.equals("CLASS TWO")) {
             try {
            // Class.forName("com.mysql.jdbc.Driver);
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/alokito","root","root");
            PreparedStatement stm = conn.prepareStatement("INSERT INTO resulttwo VALUES(?,?,?,?,?,?,?,?,?,?,?)");
            String status = gradeprepare();
            double idd= Double.parseDouble(comroll.getSelectedItem().toString());
            String names = name.getText();
            double bangla1 = Double.parseDouble(bn1ttl.getText());
            double bangla2 = Double.parseDouble(bn2ttl.getText());
            double english1 = Double.parseDouble(en1.getText());
            double english2 = Double.parseDouble(en2.getText());
            double maths = Double.parseDouble(mathg.getText());
            double religion = Double.parseDouble(rlg.getText());
            double ict = Double.parseDouble(ictg.getText());
            stm.setDouble(1, idd);
            stm.setString(2, names);
            stm.setDouble(3, bangla1);
            stm.setDouble(4, bangla2);
            stm.setDouble(5, english1);
            stm.setDouble(6, english2);
            stm.setDouble(7, maths);
            stm.setDouble(8, religion);
            stm.setDouble(9, ict);
            stm.setString(10, status);
            stm.setString(11, term);
            stm.executeUpdate();
                 System.out.println("RESULT PUBLISHED CLASS TWO");
            conn.close();
        } catch (Exception e) {
            System.out.println(""+e);
        }
        }else if (tablename.equals("CLASS THREE")) {
             try {
            // Class.forName("com.mysql.jdbc.Driver);
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/alokito","root","root");
            PreparedStatement stm = conn.prepareStatement("INSERT INTO resultthree VALUES(?,?,?,?,?,?,?,?,?,?,?)");
            String status = gradeprepare();
            double idd= Double.parseDouble(comroll.getSelectedItem().toString());
            String names = name.getText();
            double bangla1 = Double.parseDouble(bn1ttl.getText());
            double bangla2 = Double.parseDouble(bn2ttl.getText());
            double english1 = Double.parseDouble(en1.getText());
            double english2 = Double.parseDouble(en2.getText());
            double maths = Double.parseDouble(mathg.getText());
            double religion = Double.parseDouble(rlg.getText());
            double ict = Double.parseDouble(ictg.getText());
            stm.setDouble(1, idd);
            stm.setString(2, names);
            stm.setDouble(3, bangla1);
            stm.setDouble(4, bangla2);
            stm.setDouble(5, english1);
            stm.setDouble(6, english2);
            stm.setDouble(7, maths);
            stm.setDouble(8, religion);
            stm.setDouble(9, ict);
            stm.setString(10, status);
            stm.setString(11, term);
            stm.executeUpdate();
                 System.out.println("RESULT PUBLISHED CLASS THREE");
            conn.close();
        } catch (Exception e) {
            System.out.println(""+e);
        }
        }else if (tablename.equals("CLASS FOUR")) {
             try {
            // Class.forName("com.mysql.jdbc.Driver);
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/alokito","root","root");
            PreparedStatement stm = conn.prepareStatement("INSERT INTO resultfour VALUES(?,?,?,?,?,?,?,?,?,?,?)");
            String status = gradeprepare();
            double idd= Double.parseDouble(comroll.getSelectedItem().toString());
            String names = name.getText();
            double bangla1 = Double.parseDouble(bn1ttl.getText());
            double bangla2 = Double.parseDouble(bn2ttl.getText());
            double english1 = Double.parseDouble(en1.getText());
            double english2 = Double.parseDouble(en2.getText());
            double maths = Double.parseDouble(mathg.getText());
            double religion = Double.parseDouble(rlg.getText());
            double ict = Double.parseDouble(ictg.getText());
            stm.setDouble(1, idd);
            stm.setString(2, names);
            stm.setDouble(3, bangla1);
            stm.setDouble(4, bangla2);
            stm.setDouble(5, english1);
            stm.setDouble(6, english2);
            stm.setDouble(7, maths);
            stm.setDouble(8, religion);
            stm.setDouble(9, ict);
            stm.setString(10, status);
            stm.setString(11, term);
            stm.executeUpdate();
                 System.out.println("RESULT PUBLISHED CLASS FOUR");
            conn.close();
        } catch (Exception e) {
                 System.out.println(""+e);
        }
        }else if (tablename.equals("CLASS FIVE")) {
             try {
            // Class.forName("com.mysql.jdbc.Driver);
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/alokito","root","root");
            PreparedStatement stm = conn.prepareStatement("INSERT INTO resultfive VALUES(?,?,?,?,?,?,?,?,?,?,?)");
            String status = gradeprepare();
            double idd= Integer.parseInt(comroll.getSelectedItem().toString());
            String names = name.getText();
            double bangla1 = Double.parseDouble(bn1ttl.getText());
            double bangla2 = Double.parseDouble(bn2ttl.getText());
            double english1 = Double.parseDouble(en1.getText());
            double english2 = Double.parseDouble(en2.getText());
            double maths = Double.parseDouble(mathg.getText());
            double religion = Double.parseDouble(rlg.getText());
            double ict = Double.parseDouble(ictg.getText());
            stm.setDouble(1, idd);
            stm.setString(2, names);
            stm.setDouble(3, bangla1);
            stm.setDouble(4, bangla2);
            stm.setDouble(5, english1);
            stm.setDouble(6, english2);
            stm.setDouble(7, maths);
            stm.setDouble(8, religion);
            stm.setDouble(9, ict);
            stm.setString(10, status);
            stm.setString(11, term);
            stm.executeUpdate();
                 System.out.println("RESULT PUBLISHED CLASS FIVE");
            conn.close();
        } catch (Exception e) {
            System.out.println(""+e);
        }
        }
       
    }

    public void nextf(){
     int idd= Integer.parseInt(comroll.getSelectedItem().toString());
     System.out.println(""+idd);
      String names = name.getText();
        
      double bangla1 = Double.parseDouble(bn1ttl.getText());
      double bangla2 = Double.parseDouble(bn2ttl.getText());
      double english1 = Double.parseDouble(en1.getText());
      double english2 = Double.parseDouble(en2.getText());
        double maths = Double.parseDouble(mathttl.getText());
       double religion = Double.parseDouble(rlttl.getText());
        double icts = Double.parseDouble(ictttl.getText());
        
        double bnglagpa = Double.parseDouble(bng.getText());
        String banglagrade = gradeforall(bnglagpa);
        double enggpa = Double.parseDouble(eng.getText());
        String enggrade = gradeforall(enggpa);
        double mathsg = Double.parseDouble(mathg.getText());
        String mathgrade = gradeforall(mathsg);
        double relg = Double.parseDouble(rlg.getText());
        String relgrade = gradeforall(relg);
        double ictgr = Double.parseDouble(ictg.getText());
        String ictgrade = gradeforall(ictgr);
//        
//        double bngs = Double.parseDouble(bng.getText());
//        double engs = Double.parseDouble(eng.getText());
//        double mathss = Double.parseDouble(mathg.getText());
//        double rels = Double.parseDouble(rlg.getText());
//        double ictts = Double.parseDouble(ictg.getText());

       //idd,names, bangla1, bangla2, english1,english2,maths, religion,icts, bngs,engs,mathss,rels,ictts,stat
       String stat = gradeprepare();
        ProgressReport pr = new ProgressReport(idd,names,bangla1, bangla2, english1,english2, maths, religion, icts,stat, banglagrade,enggrade,mathgrade,relgrade,ictgrade);
         pr.setVisible(true);
          
//           int religion = Integer.parseInt(rlg.getText());
//          int ict = Integer.parseInt(ictg.getText());
       
    }
    public void defaults(){
    bn1s.setText(""+25);
    bn1o.setText(""+25);
    bn2s.setText(""+25);
    bn2o.setText(""+25);
    en1.setText(""+35);
    en2.setText(""+45);
    maths.setText(""+45);
    matho.setText(""+35);
    rls.setText(""+45);
    rlo.setText(""+25);
    icts.setText(""+25);
    icto.setText(""+25);
}
    private void engActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_engActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_engActionPerformed

    private void mathttlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mathttlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mathttlActionPerformed

    private void rlttlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rlttlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rlttlActionPerformed

    private void rlgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rlgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rlgActionPerformed

    private void bngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bngActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bngActionPerformed

    private void ictgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ictgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ictgActionPerformed

    private void mathgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mathgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mathgActionPerformed

    private void bnavgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnavgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bnavgActionPerformed

    private void comclassItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comclassItemStateChanged
        change();
    }//GEN-LAST:event_comclassItemStateChanged

    private void comrollItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comrollItemStateChanged
        // nameauto();
        nameauto();
    }//GEN-LAST:event_comrollItemStateChanged

    private void bn1oKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bn1oKeyReleased
        marksauto();
    }//GEN-LAST:event_bn1oKeyReleased

    private void bn2oKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bn2oKeyReleased
        // TODO add your handling code here:
        marksauto();
        banglaresultauto();
    }//GEN-LAST:event_bn2oKeyReleased

    private void en2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_en2KeyReleased
        marksauto();
        englishresultauto();
    }//GEN-LAST:event_en2KeyReleased

    private void mathoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mathoKeyReleased
        marksauto();
        mathsresultauto();
    }//GEN-LAST:event_mathoKeyReleased

    private void rloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rloKeyReleased
        marksauto();
        relresultauto();
    }//GEN-LAST:event_rloKeyReleased

    private void ictoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ictoKeyReleased
        marksauto();
        ictresultauto();
    }//GEN-LAST:event_ictoKeyReleased

    private void bnavgKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bnavgKeyReleased
//        marksauto();
    }//GEN-LAST:event_bnavgKeyReleased

    private void bn2ttlKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bn2ttlKeyReleased
//        marksauto();

    }//GEN-LAST:event_bn2ttlKeyReleased

    private void bn2ttlCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_bn2ttlCaretPositionChanged
        //resultauto();
    }//GEN-LAST:event_bn2ttlCaretPositionChanged

    private void bn2ttlCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_bn2ttlCaretUpdate

    }//GEN-LAST:event_bn2ttlCaretUpdate

    private void bn2ttlPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_bn2ttlPropertyChange
        //resultauto();
    }//GEN-LAST:event_bn2ttlPropertyChange

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        resultpush();
       nextf();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        defaults();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_jLabel19MouseClicked

    /**
     * @param args the command line arguments
     * 
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PreapareResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PreapareResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PreapareResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PreapareResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PreapareResult().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bn1o;
    private javax.swing.JTextField bn1s;
    private javax.swing.JTextField bn1ttl;
    private javax.swing.JTextField bn2o;
    private javax.swing.JTextField bn2s;
    private javax.swing.JTextField bn2ttl;
    private javax.swing.JTextField bnavg;
    private javax.swing.JTextField bng;
    private javax.swing.JComboBox<String> comclass;
    private javax.swing.JComboBox<String> comroll;
    private javax.swing.JComboBox<String> comterm;
    private javax.swing.JTextField en1;
    private javax.swing.JTextField en2;
    private javax.swing.JTextField enavg;
    private javax.swing.JTextField eng;
    private javax.swing.JTextField ictg;
    private javax.swing.JTextField icto;
    private javax.swing.JTextField icts;
    private javax.swing.JTextField ictttl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField mathg;
    private javax.swing.JTextField matho;
    private javax.swing.JTextField maths;
    private javax.swing.JTextField mathttl;
    private javax.swing.JTextField name;
    private javax.swing.JTextField rlg;
    private javax.swing.JTextField rlo;
    private javax.swing.JTextField rls;
    private javax.swing.JTextField rlttl;
    // End of variables declaration//GEN-END:variables
}
