/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smsproject;

import java.awt.Color;

/**
 *
 * @author Shaariful Islam
 */
public class ProgressReport extends javax.swing.JFrame {

    /**
     * Creates new form ProgressReport
     */
    public ProgressReport() {
        initComponents();
//jPanel1.setBackground(new Color(0,0,0,200));
        }
    public ProgressReport(double idd, String names,double bangla1,double bangla2,double english1,double english2, double math, double rel, double ict,String stats,String banglagrade, String englishgrade, String mathgrade, String relgrade, String ictgrade) {
        initComponents();
        id1.setText(""+idd);
        name.setText(names);
        bn1m.setText(""+bangla1);
        bn2m.setText(""+bangla2);
        en1m.setText(""+bangla2);
        en2m.setText(""+bangla2);
        mathm.setText(""+math);
        rlm.setText(""+rel);
        ictm.setText(""+ict);
        grade.setText(stats);
        bn1g.setText(banglagrade);
        en1g.setText(englishgrade);
        mathg.setText(mathgrade);
        rlg.setText(relgrade);
        ictg.setText(ictgrade);
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        grade = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        id = new javax.swing.JLabel();
        id2 = new javax.swing.JLabel();
        id3 = new javax.swing.JLabel();
        id4 = new javax.swing.JLabel();
        id5 = new javax.swing.JLabel();
        bn1g = new javax.swing.JLabel();
        id7 = new javax.swing.JLabel();
        id8 = new javax.swing.JLabel();
        id9 = new javax.swing.JLabel();
        id10 = new javax.swing.JLabel();
        bn1m = new javax.swing.JLabel();
        bn2m = new javax.swing.JLabel();
        en1g = new javax.swing.JLabel();
        en1m = new javax.swing.JLabel();
        en2m = new javax.swing.JLabel();
        mathg = new javax.swing.JLabel();
        mathm = new javax.swing.JLabel();
        rlm = new javax.swing.JLabel();
        rlg = new javax.swing.JLabel();
        ictm = new javax.swing.JLabel();
        ictg = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        id1 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        grade.setFont(new java.awt.Font("Poor Richard", 1, 64)); // NOI18N
        grade.setForeground(new java.awt.Color(153, 0, 153));
        grade.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        grade.setText("A+");
        jPanel2.add(grade, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 180, 200));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/quality-badge.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 280, 290));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jLabel1.setText("ID");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 109, -1));

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        id.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        id.setForeground(new java.awt.Color(255, 255, 255));
        id.setText("BANGLA FIRST");
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 190, -1));

        id2.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        id2.setForeground(new java.awt.Color(255, 255, 255));
        id2.setText("MATHEMATICS");
        jPanel1.add(id2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 230, -1));

        id3.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        id3.setForeground(new java.awt.Color(255, 255, 255));
        id3.setText("BANGLA SECOND");
        jPanel1.add(id3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 210, -1));

        id4.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        id4.setForeground(new java.awt.Color(255, 255, 255));
        id4.setText("ENGLISH FIRST");
        jPanel1.add(id4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 210, -1));

        id5.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        id5.setForeground(new java.awt.Color(255, 255, 255));
        id5.setText("GRADE");
        jPanel1.add(id5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 100, -1));

        bn1g.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        bn1g.setForeground(new java.awt.Color(51, 255, 0));
        bn1g.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bn1g.setText("ICT");
        jPanel1.add(bn1g, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 109, -1));

        id7.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        id7.setForeground(new java.awt.Color(255, 255, 255));
        id7.setText("RELIGION");
        jPanel1.add(id7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 109, -1));

        id8.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        id8.setForeground(new java.awt.Color(255, 255, 255));
        id8.setText("ENGLISH SECOND");
        jPanel1.add(id8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 220, -1));

        id9.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        id9.setForeground(new java.awt.Color(255, 255, 255));
        id9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        id9.setText("MARKS");
        jPanel1.add(id9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 120, -1));

        id10.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        id10.setForeground(new java.awt.Color(255, 255, 255));
        id10.setText("ICT");
        jPanel1.add(id10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 109, -1));

        bn1m.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        bn1m.setForeground(new java.awt.Color(255, 255, 255));
        bn1m.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bn1m.setText("ICT");
        jPanel1.add(bn1m, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 109, -1));

        bn2m.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        bn2m.setForeground(new java.awt.Color(255, 255, 255));
        bn2m.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bn2m.setText("ICT");
        jPanel1.add(bn2m, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 109, -1));

        en1g.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        en1g.setForeground(new java.awt.Color(51, 255, 0));
        en1g.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        en1g.setText("ICT");
        jPanel1.add(en1g, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 109, -1));

        en1m.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        en1m.setForeground(new java.awt.Color(255, 255, 255));
        en1m.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        en1m.setText("ICT");
        jPanel1.add(en1m, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 109, -1));

        en2m.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        en2m.setForeground(new java.awt.Color(255, 255, 255));
        en2m.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        en2m.setText("ICT");
        jPanel1.add(en2m, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 109, -1));

        mathg.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        mathg.setForeground(new java.awt.Color(51, 255, 0));
        mathg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mathg.setText("ICT");
        jPanel1.add(mathg, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 109, -1));

        mathm.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        mathm.setForeground(new java.awt.Color(255, 255, 255));
        mathm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mathm.setText("ICT");
        jPanel1.add(mathm, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 109, -1));

        rlm.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        rlm.setForeground(new java.awt.Color(255, 255, 255));
        rlm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rlm.setText("ICT");
        jPanel1.add(rlm, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 109, -1));

        rlg.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        rlg.setForeground(new java.awt.Color(51, 255, 0));
        rlg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rlg.setText("ICT");
        jPanel1.add(rlg, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 109, -1));

        ictm.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        ictm.setForeground(new java.awt.Color(255, 255, 255));
        ictm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ictm.setText("ICT");
        jPanel1.add(ictm, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 109, -1));

        ictg.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        ictg.setForeground(new java.awt.Color(51, 255, 0));
        ictg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ictg.setText("ICT");
        jPanel1.add(ictg, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, 109, -1));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 620, 400));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jLabel5.setText("NAME");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 109, -1));

        name.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        name.setText("NAME");
        jPanel2.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 330, -1));

        id1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        id1.setText("NAME");
        jPanel2.add(id1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 109, -1));

        jLabel19.setFont(new java.awt.Font("Yu Gothic Medium", 1, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 0, 0));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("X");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_jLabel19MouseClicked

    public void getresult(){
    try {
        
    } catch (Exception e) {
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProgressReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProgressReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProgressReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProgressReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProgressReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bn1g;
    private javax.swing.JLabel bn1m;
    private javax.swing.JLabel bn2m;
    private javax.swing.JLabel en1g;
    private javax.swing.JLabel en1m;
    private javax.swing.JLabel en2m;
    private javax.swing.JLabel grade;
    private javax.swing.JLabel ictg;
    private javax.swing.JLabel ictm;
    private javax.swing.JLabel id;
    private javax.swing.JLabel id1;
    private javax.swing.JLabel id10;
    private javax.swing.JLabel id2;
    private javax.swing.JLabel id3;
    private javax.swing.JLabel id4;
    private javax.swing.JLabel id5;
    private javax.swing.JLabel id7;
    private javax.swing.JLabel id8;
    private javax.swing.JLabel id9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel mathg;
    private javax.swing.JLabel mathm;
    private javax.swing.JLabel name;
    private javax.swing.JLabel rlg;
    private javax.swing.JLabel rlm;
    // End of variables declaration//GEN-END:variables
}
