/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smsproject;

import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Shaariful Islam
 */
public class StudentAdd extends javax.swing.JFrame {

    /**
     * Creates new form StudentAdd
     */
    public StudentAdd() {
        initComponents();
        change();
        // mainpanel.setBackground(new Color(0,0,0,200));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        mainpanel = new javax.swing.JPanel();
        com = new javax.swing.JComboBox<>();
        id = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        father = new javax.swing.JTextField();
        phn = new javax.swing.JTextField();
        add = new javax.swing.JTextField();
        rd1 = new javax.swing.JRadioButton();
        rd2 = new javax.swing.JRadioButton();
        imglbl = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        rd3 = new javax.swing.JRadioButton();
        age = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButtonRegisterStudent = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainpanel.setBackground(new java.awt.Color(255, 255, 255));
        mainpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        com.setBackground(new java.awt.Color(255, 102, 0));
        com.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        com.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CLASS ONE", "CLASS TWO", "CLASS THREE", "CLASS FOUR", "CLASS FIVE" }));
        com.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comItemStateChanged(evt);
            }
        });
        mainpanel.add(com, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 410, 43));

        id.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        id.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 0, 102)));
        mainpanel.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 410, 30));

        name.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        name.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 0, 102)));
        mainpanel.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 410, 30));

        father.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        father.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        father.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 0, 102)));
        mainpanel.add(father, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 410, 30));

        phn.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        phn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        phn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 0, 102)));
        mainpanel.add(phn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 410, 30));

        add.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        add.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 0, 102)));
        mainpanel.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 410, 30));

        buttonGroup1.add(rd1);
        rd1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        rd1.setText("MALE");
        mainpanel.add(rd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 450, -1, -1));

        buttonGroup1.add(rd2);
        rd2.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        rd2.setText("FEMALE");
        mainpanel.add(rd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, -1, -1));

        imglbl.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        imglbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imglbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/profile_1.png"))); // NOI18N
        mainpanel.add(imglbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 30, 220, 230));

        jButton1.setBackground(new java.awt.Color(255, 102, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CLEAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        mainpanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 430, 300, 49));

        jButton2.setBackground(new java.awt.Color(102, 0, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("BROWSE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        mainpanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 290, 210, 40));

        buttonGroup1.add(rd3);
        rd3.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        rd3.setText("OTHERS");
        mainpanel.add(rd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 450, -1, -1));

        age.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        age.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        age.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        mainpanel.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 410, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SELECT CLASS");
        mainpanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 180, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("AVAILABLE ID");
        mainpanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 180, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("NAME");
        mainpanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 90, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("FATHERS NAME");
        mainpanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 200, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 102));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("PHONE NO.");
        mainpanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 160, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 0, 102));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("ADDRESS");
        mainpanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 130, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 0, 102));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("AGE");
        mainpanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 70, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 0, 102));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("GENDER");
        mainpanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 120, -1));

        jButtonRegisterStudent.setBackground(new java.awt.Color(102, 0, 102));
        jButtonRegisterStudent.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jButtonRegisterStudent.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegisterStudent.setText("SUBMIT");
        jButtonRegisterStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterStudentActionPerformed(evt);
            }
        });
        mainpanel.add(jButtonRegisterStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 360, 300, 49));

        getContentPane().add(mainpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1150, 580));

        jPanel2.setBackground(new java.awt.Color(102, 0, 102));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ADMISSION NEW");

        jLabel19.setFont(new java.awt.Font("Yu Gothic Medium", 1, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("X");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(288, 288, 288)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 278, Short.MAX_VALUE)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 2, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public String s;

    public void datasend() {
        try {
            //Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/alokito", "root", "password");
            System.out.println("Connected");
            PreparedStatement stm;
            String tablename = com.getSelectedItem().toString();
            int idd = Integer.parseInt(id.getText());
            String names = name.getText();
            String fathers = father.getText();
            String phns = phn.getText();
            String addrs = add.getText();
            int ages = Integer.parseInt(age.getText());
            String gen = "";
            if (rd1.isSelected()) {
                gen = "MALE";
            } else if (rd2.isSelected()) {
                gen = "FEMALE";
            } else if (rd3.isSelected()) {
                gen = "OTHERS";
            }
            if (tablename.equals("CLASS ONE")) {
                stm = conn.prepareStatement("INSERT INTO classone VALUES(?,?,?,?,?,?,?,?)");
                stm.setInt(1, idd);
                stm.setString(2, names);
                stm.setString(3, fathers);
                stm.setString(4, phns);
                stm.setString(5, addrs);
                stm.setInt(6, ages);
                stm.setString(7, gen);
                InputStream is = new FileInputStream(new File(s));
                stm.setBlob(8, is);
                stm.executeUpdate();
                JOptionPane.showMessageDialog(null, "NEW ENTRY FOR CLASS ONE");
            } else if (tablename.equals("CLASS TWO")) {
                stm = conn.prepareStatement("INSERT INTO classtwo VALUES(?,?,?,?,?,?,?,?)");

                stm.setInt(1, idd);
                stm.setString(2, names);
                stm.setString(3, fathers);
                stm.setString(4, phns);
                stm.setString(5, addrs);
                stm.setInt(6, ages);
                stm.setString(7, gen);
                InputStream is = new FileInputStream(new File(s));
                stm.setBlob(8, is);
                stm.executeUpdate();
                JOptionPane.showMessageDialog(null, "NEW ENTRY FOR CLASS TWO");
            } else if (tablename.equals("CLASS THREE")) {
                stm = conn.prepareStatement("INSERT INTO classthree VALUES(?,?,?,?,?,?,?,?)");
                stm.setInt(1, idd);
                stm.setString(2, names);
                stm.setString(3, fathers);
                stm.setString(4, phns);
                stm.setString(5, addrs);
                stm.setInt(6, ages);
                stm.setString(7, gen);
                InputStream is = new FileInputStream(new File(s));
                stm.setBlob(8, is);
                stm.executeUpdate();
                JOptionPane.showMessageDialog(null, "NEW ENTRY FOR CLASS THREE");
            } else if (tablename.equals("CLASS FOUR")) {
                stm = conn.prepareStatement("INSERT INTO classfour VALUES(?,?,?,?,?,?,?,?)");
                stm.setInt(1, idd);
                stm.setString(2, names);
                stm.setString(3, fathers);
                stm.setString(4, phns);
                stm.setString(5, addrs);
                stm.setInt(6, ages);
                stm.setString(7, gen);
                InputStream is = new FileInputStream(new File(s));
                stm.setBlob(8, is);
                stm.executeUpdate();
                JOptionPane.showMessageDialog(null, "NEW ENTRY FOR CLASS FOUR");
            } else if (tablename.equals("CLASS FIVE")) {
                stm = conn.prepareStatement("INSERT INTO classfive VALUES(?,?,?,?,?,?,?,?)");
                stm.setInt(1, idd);
                stm.setString(2, names);
                stm.setString(3, fathers);
                stm.setString(4, phns);
                stm.setString(5, addrs);
                stm.setInt(6, ages);
                stm.setString(7, gen);
                InputStream is = new FileInputStream(new File(s));
                stm.setBlob(8, is);
                stm.executeUpdate();
                JOptionPane.showMessageDialog(null, "NEW ENTRY FOR CLASS FIVE");
            }

        } catch (Exception e) {
            System.out.println("" + e);
            JOptionPane.showMessageDialog(null, "Fill up all the fields with valid information!");
        }
    }
    public void clearall(){
        
            id.setText("");
            name.setText("");
            father.setText("");
            phn.setText("");
            add.setText("");
            age.setText("");
            imglbl.setText("");
            buttonGroup1.clearSelection();
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //datasend();
        clearall();
    }//GEN-LAST:event_jButton1ActionPerformed


    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        imgload();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void comItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comItemStateChanged
        change();
        name.setText("");
        father.setText("");
        phn.setText("");
        add.setText("");
        age.setText("");
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_comItemStateChanged

    private void jButtonRegisterStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterStudentActionPerformed
        // TODO add your handling code here:
        datasend();
    }//GEN-LAST:event_jButtonRegisterStudentActionPerformed

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_jLabel19MouseClicked
    public void change() {
        String tablename = com.getSelectedItem().toString();
        if (tablename.equals("CLASS ONE")) {
            try {
                //Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/alokito", "root", "password");
                System.out.println("Success");
                PreparedStatement stm = conn.prepareStatement("select id from classone");
                ResultSet res = stm.executeQuery();
                int idd = 1;
                while (res.next()) {
                    int value = res.getInt(1);
                    idd = value + 1;
                }
                id.setText("" + idd);
                conn.close();
            } catch (Exception ex) {
                System.out.println("The Exception is : " + ex);
            }
        } else if (tablename.equals("CLASS TWO")) {
            try {
                //Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/alokito", "root", "password");
                System.out.println("Success");
                PreparedStatement stm = conn.prepareStatement("select id from classtwo");
                ResultSet res = stm.executeQuery();
                int idd = 1;
                while (res.next()) {
                    int value = res.getInt(1);
                    idd = value + 1;
                }
                id.setText("" + idd);
                conn.close();
            } catch (Exception ex) {
                System.out.println("The Exception is : " + ex);
            }
        } else if (tablename.equals("CLASS THREE")) {
            try {
                //Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/alokito", "root", "password");
                System.out.println("Success");
                PreparedStatement stm = conn.prepareStatement("select id from classthree");
                ResultSet res = stm.executeQuery();
                int idd = 1;
                while (res.next()) {
                    int value = res.getInt(1);
                    idd = value + 1;
                }
                id.setText("" + idd);
                conn.close();
            } catch (Exception ex) {
                System.out.println("The Exception is : " + ex);
            }
        } else if (tablename.equals("CLASS FOUR")) {
            try {
                //Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/alokito", "root", "password");
                System.out.println("Success");
                PreparedStatement stm = conn.prepareStatement("select id from classfour");
                ResultSet res = stm.executeQuery();
                int idd = 1;
                while (res.next()) {
                    int value = res.getInt(1);
                    idd = value + 1;
                }
                id.setText("" + idd);
                conn.close();
            } catch (Exception ex) {
                System.out.println("The Exception is : " + ex);
            }
        } else if (tablename.equals("CLASS FIVE")) {
            try {
                //Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/alokito", "root", "password");
                System.out.println("Success");
                PreparedStatement stm = conn.prepareStatement("select id from classfive");
                ResultSet res = stm.executeQuery();
                int idd = 1;
                while (res.next()) {
                    int value = res.getInt(1);
                    idd = value + 1;
                }
                id.setText("" + idd);
                conn.close();
            } catch (Exception ex) {
                System.out.println("The Exception is : " + ex);
            }
        }

    }

    public void imgload() {
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Image", "jpg", "gif", "png");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selected = file.getSelectedFile();
            String path = selected.getAbsolutePath();
            imglbl.setIcon(ResizeImage(path));
            s = path;
        }
    }
//   public void sendimg(){
//        try {
//             
//            //Class.forName("com.mysql.jdbc.Driver");
//            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/mysdb","root","root");
//            System.out.println("Success");
//            PreparedStatement stm = conn.prepareStatement("insert into image values(?)");
//            InputStream is = new FileInputStream(new File(s));
//            stm.setBlob(1, is);
//           stm.executeUpdate();
//            
//            conn.close();
//        } catch (Exception ex) {
//            System.out.println("The Exception is : "+ex);
//        }  
//    }  

    public ImageIcon ResizeImage(String ImagePath) {
        ImageIcon myimg = new ImageIcon(ImagePath);
        Image img = myimg.getImage();
        Image newImg = img.getScaledInstance(imglbl.getWidth(), imglbl.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField add;
    private javax.swing.JTextField age;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> com;
    private javax.swing.JTextField father;
    private javax.swing.JTextField id;
    private javax.swing.JLabel imglbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonRegisterStudent;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JTextField name;
    private javax.swing.JTextField phn;
    private javax.swing.JRadioButton rd1;
    private javax.swing.JRadioButton rd2;
    private javax.swing.JRadioButton rd3;
    // End of variables declaration//GEN-END:variables
}
